# Generated by Django 4.2.1 on 2023-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='ФИО:')),
                ('employee_birthdate', models.DateField(blank=True, verbose_name='Дата рождения:')),
                ('employee_post', models.CharField(choices=[(1, 'Генеральный директор'), (2, 'Главный бухгалтер'), (3, 'Исполнительный директор')], default='Генеральный директор', max_length=200)),
            ],
        ),
    ]
