# Generated by Django 4.2.1 on 2023-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_post',
            field=models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Главный бухгалтер', 'Главный бухгалтер'), ('Исполнительный директор', 'Исполнительный директор')], max_length=200),
        ),
    ]
