# Generated by Django 4.2.1 on 2023-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_employee_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_post',
            field=models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Главный бухгалтер', 'Главный бухгалтер'), ('Исполнительный директор', 'Исполнительный директор')], max_length=200, verbose_name='Должность сотрудника:'),
        ),
    ]
