# Generated by Django 4.2.1 on 2023-06-03 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_employee_employee_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_theme', models.CharField(max_length=200, verbose_name='Тема:')),
                ('instruction_create_date', models.DateField(default=datetime.date(2023, 6, 3), verbose_name='Дата создания:')),
                ('instruction_link', models.URLField(verbose_name='Ссылка на файл:')),
                ('instruction_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
    ]
